#region 

perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out   /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype phastConsElements100way /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype cytoBand /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype wgRna /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/  -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype tfbsConsSites /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
#TargetScan predicts biological targets of miRNAs by searching for the presence of conserved 8mer, 7mer, and 6mer sites
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype targetScanS /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/  -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype genomicSuperDups /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype dgvMerged /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10  
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -build hg38 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -dbtype gwasCatalog /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -dbtype wgEncodeCaltechRnaSeqRawSignalRep1Gm12878CellLongpolyaBb12x75 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/  -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -dbtype wgEncodeBroadChipSeqPeaksGm12878H3k4me1 -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -regionanno -dbtype wgEncodeRegDnaseClustered /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/  -out  /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_region -thread 10 

#gene
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/gene/hgmd/hgmd_gene --geneanno -dbtype refGene -build hg38 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -aamatrixfile grantham.matrix -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene  -buildver hg38 -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl  -build hg38 -hgvs /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/gene/hgmd/hgmd_gene -build hg38 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -dbtype knownGene -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/gene/hgmd/hgmd_gene -build hg38 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -dbtype ensGene -thread 10 
#perl annotate_variation.pl --downdb wgEncodeGencodeBasicV27 /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb -build hg38 -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -build hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/gene/hgmd/hgmd_gene -dbtype wgEncodeGencodeBasicV27 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 

#filter

#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype 1000g2012apr_eur -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -filter -build hg38 -dbtype avsnp142 -thread 10 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/filter/hgmd/hgmd_filter
perl table_annovar.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -protocol dbnsfp30a -operation f -build hg38 -nastring . -thread 10 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/filter/hgmd/hgmd_filter
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_sift -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/  -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_pp2hvar -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_mt -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_ma -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_lrt -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_fathmm -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_metasvm -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_metalr -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_gerp++ -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_phylop -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype ljb23_siphy -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -dbtype esp6500siv2_all -build hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/filter/hgmd/hgmd_filter /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -build hg38 -dbtype exac03 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -otherinfo -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput  /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -dbtype gerp++gt2 -build hg38 -filter -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene -dbtype popfreq_max_20150413 -build hg38 /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -filter -dbtype clinvarMain -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene -thread 10 
#perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -filter -dbtype cadd -buildver hg38 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/region/hgmd/hgmd_gene -thread 10 
perl /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/annotate_variation.pl -filter /mnt/workspace/prabakaranLab/sorfcScore/data/variantMapToSorfs/hgmd/hgmd_sorf_mutation.avinput /mnt/workspace/prabakaranLab/sorfcScore/software/annovar/humandb/ -dbtype eigen -build hg38 -thread 10 -out /mnt/workspace/prabakaranLab/sorfcScore/data/annotation/filter/hgmd/hgmd_filter





